server:
  port: 8888
  servlet:
    context-path: /kien


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/password_store
    username: postgres
    password: kientran2001

  mvc:
    view:
      prefix: /views/
      suffix: .jsp
# tự động tìm các path để generate (API document)
    pathmatch:
      matching-strategy: ant_path_matcher

